version: '3.8'

services:
  rsyslog:
    image: rsyslog/syslog_appliance_alpine:latest
    container_name: rsyslog-server
    ports:
      - "514:514/udp"
      - "514:514/tcp"
    volumes:
      - ./config/rsyslog.conf:/etc/rsyslog.conf
      - ./logs:/logs
    restart: always
